/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package odontologicaescritorio.vista;

import javax.swing.table.DefaultTableModel;
import odontologicaescritorio.controlador.*;
import odontologicaescritorio.modelo.*;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;

/**
 *
 * @author Marco Antonio
 */
public class ItinerarioHoras extends javax.swing.JInternalFrame {

    /**
     * Creates new form ItinerarioHoras
     */
    public ItinerarioHoras() {
        initComponents();
        
        double totalHoras = new Hora().obtenerMaximoTotalHorasJornadaBD(1, 2018);
        ArrayList<DiaDTO> listaDias = new Hora().obtenerDiasPorFuncionario(19516774);
        ArrayList<HoraDTO> listaHoras = new Hora().obtenerHorasPorFuncionario(19516774, 1, 2018);
        LocalTime[] limiteHoras = new Hora().obtenerMaximoLargoJornada(1, 2018);
        
        String matriz[][] = new String[((int)totalHoras * 2) + 1 + 2] //Se deja espacio para la columna de horas.
                                      [listaDias.size() + 1]; //Se deja espacio para la fila de días.
                                      
        //Definir cabecera de la tabla.
        String[] columnas;
        matriz[0][0] = "Hora/Dia";
        System.out.print(matriz[0][0]);
        
        //Llenar cabecera de días.
        for(int i = 0; i < listaDias.size(); i++){
            matriz[0][i + 1] = String.valueOf(listaDias.get(i).getDia().getDayOfMonth());
            System.out.print(" " + matriz[0][i + 1]);
        }
        System.out.println();
        //LLenar columna de horas.
        LocalTime contadorHoras = limiteHoras[0];
        for(int y = 1; y < (totalHoras*2) + 2; y++){ 
            matriz[y][0] = contadorHoras.toString();
            System.out.println(matriz[y][0]);
            contadorHoras = contadorHoras.plusMinutes(30);
        }
        
        for(int y = 0; y < matriz.length; y++){
            for(int x = 0; x < matriz[0].length; x++){
                for(HoraDTO hora : listaHoras){
                    if((String.valueOf(hora.getFecha().getDayOfMonth()).equals(matriz[0][x])) && (hora.getHora().toString().equals(matriz[y][0]))){
                        matriz[y][x] = "HR";
                    }
                }
            }
        }
        
        //-- JTABLE NO TOCAR --
        
        columnas = matriz[0];
        
        DefaultTableModel modeloTabla = new DefaultTableModel(columnas, 0){
            //Modificamos la primera columna, de tal manera que:
            //No sea editable.
            @Override
            public boolean isCellEditable(int row, int column){
                if (0 == column)
                    return false;
                return super.isCellEditable(row, column);
            }                      
        };
        
        //Modificamos la primera columna, de tal manera que:
        //Parezca cabecera.
        tblHorario.getColumnModel().getColumn(0).setCellRenderer(tblHorario.getTableHeader().getDefaultRenderer());        
        
        //Agrega las columnas, excepto la primera, que contiene las cabeceras.
        for(int i = 1; i < matriz.length; i++ ){
            modeloTabla.addRow(matriz[i]);
        }
        
        //Finalizamos formateo de tabla
        tblHorario.setModel(modeloTabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHorario = new javax.swing.JTable();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        tblHorario.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        tblHorario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblHorario);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHorario;
    // End of variables declaration//GEN-END:variables
}
