/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package odontologicaescritorio.vista;
import javax.swing.table.DefaultTableModel;
import odontologicaescritorio.modelo.*;
import odontologicaescritorio.controlador.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Marco Antonio
 */
public class ManejadorProveedores extends javax.swing.JInternalFrame {

    /**
     * Creates new form ManejadorProveedores
     */
    private ArrayList<ProveedorDTO> listaProveedores;
    public ManejadorProveedores() {
        initComponents();
        for(RubroDTO rubro : new Lista().listarRubros()){
            cboRubroProveedor.addItem(rubro.getIdDescripcion());
        }
        actualizarListaFuncionarios();
    }
    
    public void actualizarListaFuncionarios(){
        listaProveedores = new Lista().listarProveedores();
        String[] columnas = {"RUT","Nombres", "Apellidos"};
        DefaultTableModel modeloTabla = new DefaultTableModel(columnas, 0);
        
        for(ProveedorDTO proveedor : listaProveedores){
            String rut      = proveedor.getRutEmpresa() + "-" + proveedor.getDvEmpresa();
            String nombre   = proveedor.getNombreEmpresa();
            int telefono = proveedor.getTelefono();
            Object[] elemento = {rut, nombre, telefono};
            modeloTabla.addRow(elemento);
        };
        tblProveedores.setModel(modeloTabla);        
    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblListaPersonas3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cboDvProveedor = new javax.swing.JComboBox<>();
        txtRUTProveedor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cboRubroProveedor = new javax.swing.JComboBox<>();
        lblListaPersonas5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtRutRepresentante = new javax.swing.JTextField();
        cboDvRepresentante = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNombreRepresentante = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblModo = new javax.swing.JLabel();
        btnEditarDatos = new javax.swing.JButton();
        btnCancelarEdicion = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtNombreProveedor = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblListaPersonas4 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txtRutBusqueda = new javax.swing.JTextField();
        btnBuscarRUT = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProveedores = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        btnCargarFichaProveedor = new javax.swing.JButton();
        btnRegistrarProveedor = new javax.swing.JButton();

        setBackground(new java.awt.Color(139, 156, 168));
        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Manejo de proveedores");

        jPanel1.setBackground(new java.awt.Color(218, 210, 226));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblListaPersonas3.setBackground(new java.awt.Color(146, 128, 183));
        lblListaPersonas3.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblListaPersonas3.setForeground(new java.awt.Color(255, 255, 255));
        lblListaPersonas3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_producto.png"))); // NOI18N
        lblListaPersonas3.setText("Datos del proveedor");
        lblListaPersonas3.setOpaque(true);

        jLabel12.setText("-");

        cboDvProveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "K" }));
        cboDvProveedor.setEnabled(false);

        txtRUTProveedor.setEditable(false);

        jLabel3.setText("RUT y digito verificador (persona jurídica):");

        jLabel4.setText("Teléfono de contacto:");

        txtTelefono.setEditable(false);

        jLabel5.setText("Email:");

        txtEmail.setEditable(false);

        jLabel6.setText("Rubro del proveedor:");

        cboRubroProveedor.setEnabled(false);

        lblListaPersonas5.setBackground(new java.awt.Color(146, 128, 183));
        lblListaPersonas5.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblListaPersonas5.setForeground(new java.awt.Color(255, 255, 255));
        lblListaPersonas5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_persona.png"))); // NOI18N
        lblListaPersonas5.setText("Datos del representante");
        lblListaPersonas5.setOpaque(true);

        jLabel7.setText("RUT y digito verificador:");

        txtRutRepresentante.setEditable(false);

        cboDvRepresentante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "K" }));
        cboDvRepresentante.setEnabled(false);

        jLabel14.setText("-");

        jLabel8.setText("Nombre del representante:");

        txtNombreRepresentante.setEditable(false);

        jLabel1.setText("ID proveedor:");

        jLabel2.setText("-");

        lblModo.setBackground(new java.awt.Color(204, 255, 204));
        lblModo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_ver.png"))); // NOI18N
        lblModo.setText("Usted está en modo vista.");
        lblModo.setOpaque(true);

        btnEditarDatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_editar.png"))); // NOI18N
        btnEditarDatos.setText("Editar datos");
        btnEditarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarDatosActionPerformed(evt);
            }
        });

        btnCancelarEdicion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_cancelar.png"))); // NOI18N
        btnCancelarEdicion.setText("Cancelar edición");
        btnCancelarEdicion.setEnabled(false);
        btnCancelarEdicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarEdicionActionPerformed(evt);
            }
        });

        jLabel9.setText("Nombre proveedor:");

        txtNombreProveedor.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblListaPersonas3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblListaPersonas5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreRepresentante))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addComponent(lblModo, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtRutRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboDvRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnEditarDatos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelarEdicion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtRUTProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cboDvProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                    .addGap(41, 41, 41))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(53, 53, 53)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNombreProveedor)
                                .addComponent(txtEmail)
                                .addComponent(txtTelefono)
                                .addComponent(cboRubroProveedor, 0, 265, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblModo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblListaPersonas3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtRUTProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboDvProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtNombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cboRubroProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblListaPersonas5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtRutRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboDvRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtNombreRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditarDatos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelarEdicion)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(218, 210, 226));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblListaPersonas4.setBackground(new java.awt.Color(146, 128, 183));
        lblListaPersonas4.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblListaPersonas4.setForeground(new java.awt.Color(255, 255, 255));
        lblListaPersonas4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_producto.png"))); // NOI18N
        lblListaPersonas4.setText("Lista de proveedores");
        lblListaPersonas4.setOpaque(true);

        jLabel32.setBackground(new java.awt.Color(204, 255, 204));
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_lupa.png"))); // NOI18N
        jLabel32.setText("Buscar por RUT (Ingrese sin DV):");
        jLabel32.setIconTextGap(0);
        jLabel32.setOpaque(true);

        btnBuscarRUT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_buscar.png"))); // NOI18N
        btnBuscarRUT.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnBuscarRUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarRUTActionPerformed(evt);
            }
        });

        tblProveedores.setBackground(new java.awt.Color(255, 255, 153));
        tblProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblProveedores);

        jLabel13.setBackground(new java.awt.Color(146, 128, 183));
        jLabel13.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Centro de acciones");
        jLabel13.setOpaque(true);

        btnCargarFichaProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_cargarficha.png"))); // NOI18N
        btnCargarFichaProveedor.setText("Cargar ficha");
        btnCargarFichaProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarFichaProveedorActionPerformed(evt);
            }
        });

        btnRegistrarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_agregar.png"))); // NOI18N
        btnRegistrarProveedor.setText("Registrar");
        btnRegistrarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarProveedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblListaPersonas4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtRutBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarRUT, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCargarFichaProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegistrarProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblListaPersonas4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarRUT)
                    .addComponent(txtRutBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCargarFichaProveedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistrarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarRUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarRUTActionPerformed

    }//GEN-LAST:event_btnBuscarRUTActionPerformed

    private void btnCargarFichaProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarFichaProveedorActionPerformed

    }//GEN-LAST:event_btnCargarFichaProveedorActionPerformed
    boolean estaRegistrando = false;
    private void btnRegistrarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarProveedorActionPerformed
        if(!estaRegistrando){
            estaRegistrando = true;
            txtRUTProveedor.setEditable(true);
            txtRutRepresentante.setEditable(true);
            txtEmail.setEditable(true);
            txtTelefono.setEditable(true);
            txtNombreRepresentante.setEditable(true);
            cboDvProveedor.setEnabled(true);
            cboDvRepresentante.setEnabled(true);
            cboRubroProveedor.setEnabled(true);
            btnCancelarEdicion.setEnabled(true);
            txtNombreProveedor.setEditable(true);
        }
    }//GEN-LAST:event_btnRegistrarProveedorActionPerformed
    
    boolean estaEditando = false;
    private void btnEditarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarDatosActionPerformed
        
        if(!estaEditando){
            estaEditando = true;
            txtRUTProveedor.setEditable(true);
            txtRutRepresentante.setEditable(true);
            txtEmail.setEditable(true);
            txtTelefono.setEditable(true);
            txtNombreRepresentante.setEditable(true);
            cboDvProveedor.setEnabled(true);
            cboDvRepresentante.setEnabled(true);
            cboRubroProveedor.setEnabled(true);
            btnCancelarEdicion.setEnabled(true);
            txtNombreProveedor.setEditable(true);
        }
        
        if(estaRegistrando){
            JOptionPane.showMessageDialog(rootPane, new Registro().registrarProveedorBD(txtNombreProveedor.getText(), Integer.parseInt(txtRUTProveedor.getText()), String.valueOf(cboDvProveedor.getSelectedItem()).charAt(0), Integer.parseInt(txtTelefono.getText()), txtEmail.getText(), txtNombreRepresentante.getText(), Integer.parseInt(txtRutRepresentante.getText()), String.valueOf(cboDvRepresentante.getSelectedItem()).charAt(0), String.valueOf(cboRubroProveedor.getSelectedItem())), "Registro de proveedor", HEIGHT);
            actualizarListaFuncionarios();
        }
    }//GEN-LAST:event_btnEditarDatosActionPerformed

    private void btnCancelarEdicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEdicionActionPerformed
            estaRegistrando = false;
            estaEditando = false;
            estaEditando = false;
            txtRUTProveedor.setEditable(false);
            txtRutRepresentante.setEditable(false);
            txtEmail.setEditable(false);
            txtTelefono.setEditable(false);
            txtNombreRepresentante.setEditable(false);
            cboDvProveedor.setEnabled(false);
            cboDvRepresentante.setEnabled(false);
            cboRubroProveedor.setEnabled(false);
            btnCancelarEdicion.setEnabled(false);  
    }//GEN-LAST:event_btnCancelarEdicionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarRUT;
    private javax.swing.JButton btnCancelarEdicion;
    private javax.swing.JButton btnCargarFichaProveedor;
    private javax.swing.JButton btnEditarDatos;
    private javax.swing.JButton btnRegistrarProveedor;
    private javax.swing.JComboBox<String> cboDvProveedor;
    private javax.swing.JComboBox<String> cboDvRepresentante;
    private javax.swing.JComboBox<String> cboRubroProveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblListaPersonas3;
    private javax.swing.JLabel lblListaPersonas4;
    private javax.swing.JLabel lblListaPersonas5;
    private javax.swing.JLabel lblModo;
    private javax.swing.JTable tblProveedores;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombreProveedor;
    private javax.swing.JTextField txtNombreRepresentante;
    private javax.swing.JTextField txtRUTProveedor;
    private javax.swing.JTextField txtRutBusqueda;
    private javax.swing.JTextField txtRutRepresentante;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
