/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package odontologicaescritorio.vista;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import odontologicaescritorio.controlador.*;
import odontologicaescritorio.modelo.*;

/**
 *
 * @author Marco Antonio
 */
public class ManejadorUsuarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form ManejadorUsuarios
     */
    ArrayList<UsuarioDTO> listaUsuarios;
    int permisoAdministrador = 0;
    int permisoOdontologo = 0;
    int permisoRecepcionista = 0;
    int permisoLogistica = 0;
    int permisoCliente = 0;
    public ManejadorUsuarios() {
        initComponents();
        actualizarListaUsuarios();
    }

    public void actualizarListaUsuarios(){
        listaUsuarios = new Lista().listarUsuarios();
        String[] columnas = {"ID", "Nombre"};
        DefaultTableModel modeloTabla = new DefaultTableModel(columnas, 0);
        
        for(UsuarioDTO usuario : listaUsuarios){
            String id       = String.valueOf(usuario.getId());
            String nombre   = usuario.getNombre();
            Object[] elemento = {id, nombre};
            modeloTabla.addRow(elemento);
        };
        tblPacientes.setModel(modeloTabla);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPacientes = new javax.swing.JTable();
        txtRutBusqueda = new javax.swing.JTextField();
        btnBuscarRUT = new javax.swing.JButton();
        btnVerUsuario = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        chkUsuarioAdministrador = new javax.swing.JCheckBox();
        chkUsuarioOdontologo = new javax.swing.JCheckBox();
        chkUsuarioRecepcionista = new javax.swing.JCheckBox();
        chkUsuarioLogistica = new javax.swing.JCheckBox();
        chkUsuarioCliente = new javax.swing.JCheckBox();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnReiniciarClave = new javax.swing.JButton();
        btnEditarUsuario = new javax.swing.JButton();
        lblRutPersona = new javax.swing.JLabel();
        lblIdUsuario = new javax.swing.JLabel();
        btnCancelarEdicion = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setTitle("Manejo de usuarios");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_persona.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(139, 156, 168));

        jPanel6.setBackground(new java.awt.Color(218, 210, 226));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setPreferredSize(new java.awt.Dimension(480, 461));

        tblPacientes.setBackground(new java.awt.Color(255, 255, 153));
        tblPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPacientes);

        btnBuscarRUT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_buscar.png"))); // NOI18N
        btnBuscarRUT.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnBuscarRUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarRUTActionPerformed(evt);
            }
        });

        btnVerUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_ver.png"))); // NOI18N
        btnVerUsuario.setText("Ver usuario");
        btnVerUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerUsuarioActionPerformed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(146, 128, 183));
        jLabel13.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Centro de acciones");
        jLabel13.setOpaque(true);

        jLabel14.setBackground(new java.awt.Color(146, 128, 183));
        jLabel14.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_persona.png"))); // NOI18N
        jLabel14.setText("Lista de usuarios del sistema");
        jLabel14.setOpaque(true);

        jLabel32.setBackground(new java.awt.Color(204, 255, 204));
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_lupa.png"))); // NOI18N
        jLabel32.setText("Buscar por nombre de usuario:");
        jLabel32.setIconTextGap(0);
        jLabel32.setOpaque(true);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtRutBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarRUT, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnVerUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarRUT)
                    .addComponent(txtRutBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVerUsuario)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(218, 210, 226));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel15.setBackground(new java.awt.Color(146, 128, 183));
        jLabel15.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_persona.png"))); // NOI18N
        jLabel15.setText("Datos del usuario");
        jLabel15.setOpaque(true);

        chkUsuarioAdministrador.setText("Acceso a módulo: Administrador");
        chkUsuarioAdministrador.setEnabled(false);

        chkUsuarioOdontologo.setText("Acceso a módulo: Odontólogo");
        chkUsuarioOdontologo.setEnabled(false);

        chkUsuarioRecepcionista.setText("Acceso a módulo: Recepcionista");
        chkUsuarioRecepcionista.setEnabled(false);

        chkUsuarioLogistica.setText("Acceso a módulo: Logística");
        chkUsuarioLogistica.setEnabled(false);

        chkUsuarioCliente.setText("Acceso a módulo: Cliente");
        chkUsuarioCliente.setEnabled(false);

        jLabel16.setBackground(new java.awt.Color(146, 128, 183));
        jLabel16.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_pc.png"))); // NOI18N
        jLabel16.setText("Privilegios de acceso en el sistema");
        jLabel16.setOpaque(true);

        jLabel17.setBackground(new java.awt.Color(249, 255, 211));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_advertencia.png"))); // NOI18N
        jLabel17.setText("ATENCIÓN: Modifique los privilegios de acceso con cautela.");
        jLabel17.setIconTextGap(0);
        jLabel17.setOpaque(true);

        jLabel18.setBackground(new java.awt.Color(146, 128, 183));
        jLabel18.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_llave.png"))); // NOI18N
        jLabel18.setText("Reinicio de clave");
        jLabel18.setOpaque(true);

        jLabel19.setBackground(new java.awt.Color(249, 255, 211));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_advertencia.png"))); // NOI18N
        jLabel19.setText("Se reiniciará a clave genérica: últimos 4 dígitos del RUT.");
        jLabel19.setIconTextGap(0);
        jLabel19.setOpaque(true);

        txtNombreUsuario.setEditable(false);

        jLabel7.setText("RUT de la persona:");

        jLabel8.setText("ID única del usuario:");

        jLabel3.setText("Nombre de usuario:");

        btnReiniciarClave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_refrezcar.png"))); // NOI18N
        btnReiniciarClave.setText("Reiniciar a clave genérica");
        btnReiniciarClave.setEnabled(false);

        btnEditarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_editar.png"))); // NOI18N
        btnEditarUsuario.setText("Editar datos del usuario");
        btnEditarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarUsuarioActionPerformed(evt);
            }
        });

        lblRutPersona.setText("-");

        lblIdUsuario.setText("-");

        btnCancelarEdicion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_cancelar.png"))); // NOI18N
        btnCancelarEdicion.setText("Cancelar");
        btnCancelarEdicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarEdicionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIdUsuario)
                            .addComponent(lblRutPersona)))
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReiniciarClave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkUsuarioAdministrador)
                            .addComponent(chkUsuarioOdontologo))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkUsuarioCliente)
                            .addComponent(chkUsuarioLogistica)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnCancelarEdicion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditarUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chkUsuarioRecepcionista, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblRutPersona))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblIdUsuario))
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReiniciarClave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(chkUsuarioAdministrador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkUsuarioOdontologo))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(chkUsuarioLogistica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkUsuarioCliente)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkUsuarioRecepcionista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditarUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelarEdicion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarRUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarRUTActionPerformed
        String nombreBuscar = txtRutBusqueda.getText();
        for(int i = 0; i < tblPacientes.getRowCount(); i++){
            String nombreSeleccionado  = String.valueOf(tblPacientes.getValueAt(i, 0)).split("-")[0];
            if(nombreSeleccionado.equals(nombreBuscar)){
                tblPacientes.setRowSelectionInterval(i, i);
                JOptionPane.showConfirmDialog(rootPane, "Se ha encontrado y seleccionado la incidencia.", "Usuario encontrado", WIDTH);
                return;
            }
        }
        JOptionPane.showConfirmDialog(rootPane, "La busqueda no arrojó resultados.", "Usuario no encontrado", WIDTH);
    }//GEN-LAST:event_btnBuscarRUTActionPerformed

    private void btnVerUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerUsuarioActionPerformed
        // TODO add your handling code here:
        int fila = tblPacientes.getSelectedRow();
        int rut  = Integer.parseInt(String.valueOf(tblPacientes.getValueAt(fila, 0)).split("-")[0]);
        chkUsuarioAdministrador.setSelected(false);    
        chkUsuarioOdontologo.setSelected(false);
        chkUsuarioRecepcionista.setSelected(false);
        chkUsuarioLogistica.setSelected(false);
        chkUsuarioCliente.setSelected(false);
        for(UsuarioDTO usuario : listaUsuarios){
            if(usuario.getRut_persona() == rut){
                txtNombreUsuario.setText(usuario.getNombre());
                lblIdUsuario.setText(String.valueOf(usuario.getId()));
                lblRutPersona.setText(String.valueOf(usuario.getRut_persona()));
                for(int permiso : usuario.getPermisos()){
                switch(permiso){
                    case 0:
                        chkUsuarioAdministrador.setSelected(true);
                        permisoAdministrador = 1;
                        break;
                    case 1:
                        chkUsuarioOdontologo.setSelected(true);
                        permisoOdontologo = 1;
                        break;
                    case 2:
                        chkUsuarioRecepcionista.setSelected(true);
                        permisoRecepcionista = 1;
                        break;
                    case 3:
                        chkUsuarioLogistica.setSelected(true);
                        permisoLogistica = 1;
                        break;
                    case 4:
                        chkUsuarioCliente.setSelected(true);
                        permisoCliente = 1;
                        break;
                    }
                }
            }
        }
    }//GEN-LAST:event_btnVerUsuarioActionPerformed

    boolean estaEditando = false;
    private void btnEditarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarUsuarioActionPerformed
        if(!estaEditando){
            estaEditando = true;
            //txtNombreUsuario.setEditable(true);
            btnReiniciarClave.setEnabled(true);
            chkUsuarioAdministrador.setEnabled(true);
            chkUsuarioOdontologo.setEnabled(true);
            chkUsuarioRecepcionista.setEnabled(true);
            chkUsuarioLogistica.setEnabled(true);
            chkUsuarioCliente.setEnabled(true);  
            btnEditarUsuario.setText("Guardar cambios");
            tblPacientes.setEnabled(false);
            btnVerUsuario.setEnabled(false);
            btnBuscarRUT.setEnabled(false);
            txtRutBusqueda.setEditable(false);
            btnEditarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_guardar.png")));
        }else{
            estaEditando = false;
            //txtNombreUsuario.setEditable(false);
            btnReiniciarClave.setEnabled(false);
            chkUsuarioAdministrador.setEnabled(false);
            chkUsuarioOdontologo.setEnabled(false);
            chkUsuarioRecepcionista.setEnabled(false);
            chkUsuarioLogistica.setEnabled(false);
            chkUsuarioCliente.setEnabled(false);  
            btnEditarUsuario.setText("Editar datos del usuario");
            tblPacientes.setEnabled(true);
            btnVerUsuario.setEnabled(true);        
            btnBuscarRUT.setEnabled(true);
            txtRutBusqueda.setEditable(true);
            btnEditarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_editar.png")));
            //obtener variables de permiso
            if(chkUsuarioAdministrador.isSelected()) permisoAdministrador = 1; else permisoAdministrador = 0;
            if(chkUsuarioOdontologo.isSelected()) permisoOdontologo = 1; else permisoOdontologo = 0;
            if(chkUsuarioRecepcionista.isSelected()) permisoRecepcionista = 1; else permisoRecepcionista = 0;
            if(chkUsuarioLogistica.isSelected()) permisoLogistica = 1; else permisoLogistica = 0;
            if(chkUsuarioCliente.isSelected()) permisoCliente = 1; else permisoCliente = 0;
            JOptionPane.showMessageDialog(rootPane, new Actualizacion().actualizarPermisosUsuario(Integer.parseInt(lblIdUsuario.getText()), permisoAdministrador, permisoOdontologo, permisoRecepcionista, permisoLogistica, permisoCliente), "Modificación de permisos", HEIGHT);
            actualizarListaUsuarios();
        }

    }//GEN-LAST:event_btnEditarUsuarioActionPerformed

    private void btnCancelarEdicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEdicionActionPerformed
            estaEditando = false;
            //txtNombreUsuario.setEditable(false);
            btnReiniciarClave.setEnabled(false);
            chkUsuarioAdministrador.setEnabled(false);
            chkUsuarioOdontologo.setEnabled(false);
            chkUsuarioRecepcionista.setEnabled(false);
            chkUsuarioLogistica.setEnabled(false);
            chkUsuarioCliente.setEnabled(false);  
            btnEditarUsuario.setText("Editar datos del usuario");
            tblPacientes.setEnabled(true);
            btnVerUsuario.setEnabled(true);        
            btnBuscarRUT.setEnabled(true);
            txtRutBusqueda.setEditable(true);
            btnEditarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_editar.png")));
    }//GEN-LAST:event_btnCancelarEdicionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarRUT;
    private javax.swing.JButton btnCancelarEdicion;
    private javax.swing.JButton btnEditarUsuario;
    private javax.swing.JButton btnReiniciarClave;
    private javax.swing.JButton btnVerUsuario;
    private javax.swing.JCheckBox chkUsuarioAdministrador;
    private javax.swing.JCheckBox chkUsuarioCliente;
    private javax.swing.JCheckBox chkUsuarioLogistica;
    private javax.swing.JCheckBox chkUsuarioOdontologo;
    private javax.swing.JCheckBox chkUsuarioRecepcionista;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIdUsuario;
    private javax.swing.JLabel lblRutPersona;
    private javax.swing.JTable tblPacientes;
    private javax.swing.JTextField txtNombreUsuario;
    private javax.swing.JTextField txtRutBusqueda;
    // End of variables declaration//GEN-END:variables
}
