/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package odontologicaescritorio.vista;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import odontologicaescritorio.modelo.*;
import odontologicaescritorio.controlador.*;
/**
 *
 * @author Marco Antonio
 */
public class ManejadorProductos extends javax.swing.JInternalFrame {
    private ArrayList<FamiliaProductoDTO> listaFamilias;
    private ArrayList<TipoProductoDTO> listaTipoProducto;
    private ArrayList<ProductoDTO> listaProductos;
    private ArrayList<ProveedorDTO> listaProveedores = new Lista().listarProveedores();
    /**
     * Creates new form ManejadorProductos
     */
    public ManejadorProductos() {
        initComponents();
        actualizarComponentesFamilia();
        actualizarTablaFamilia();
        actualizarTablaProducto();
        actualizarTablaTipo();
        actualizarCboTipo(cboFamiliaProducto, cboTipoProducto);
        for(ProveedorDTO proveedor : listaProveedores){
            cboProveedores.addItem(proveedor.getId() + " - " + proveedor.getNombreEmpresa());
        }
    }
    
    public void actualizarComponentesFamilia(){
        for(FamiliaProductoDTO familiaProducto : new Lista().listaFamiliasProducto()){
            cboFamiliaTipo.addItem(familiaProducto.getId() + " - " + familiaProducto.getDescripcion());
            cboFamiliaProducto.addItem(familiaProducto.getId() + " - " + familiaProducto.getDescripcion());
        }
    }
    
    public void actualizarCboTipo(javax.swing.JComboBox<String> comboBoxFamilia, javax.swing.JComboBox<String> comboBoxTipo){
        int idFamilia = Integer.parseInt(String.valueOf(comboBoxFamilia.getSelectedItem()).split(" ")[0]);
        for(TipoProductoDTO tipoProducto : new Lista().listaTiposProductoPorIdFamilia(idFamilia)){
            comboBoxTipo.addItem(tipoProducto.getId() + " - " + tipoProducto.getDescripcion());
        }        
    }
    
//    public void actualizarCboProveedores(){
//        for(ProveedorDTO proveedor : new Lista().){
//            comboBoxTipo.addItem(tipoProducto.getId() + " - " + tipoProducto.getDescripcion());
//        }        
//    }    
    
    public void actualizarTablaProducto(){
        listaProductos = new Lista().listaProductos();
        String[] columnas = {"ID","Nombre", "Precio compra", "Precio venta"};
        DefaultTableModel modeloTabla = new DefaultTableModel(columnas, 0);
        
        for(ProductoDTO producto : listaProductos){
            String id            = String.valueOf(producto.getId());
            String nombre        = producto.getNombre();
            String precioCompra  = String.valueOf(producto.getPrecioCompra());
            String precioVenta   = String.valueOf(producto.getPrecioVenta());
            String proveedor     = producto.getIdProveedor();
            String tipo          = producto.getIdTipo();
            String familia       = producto.getIdFamilia();
            Object[] elemento    = {id, nombre, precioCompra, precioVenta};
            modeloTabla.addRow(elemento);
        };
        tblProductos.setModel(modeloTabla);           
    }
    
    public void actualizarTablaTipo(){
        listaTipoProducto = new Lista().listaTiposProducto();
        String[] columnas = {"ID","Descripcion"};
        DefaultTableModel modeloTabla = new DefaultTableModel(columnas, 0);
        
        for(TipoProductoDTO tipo : listaTipoProducto){
            String id            = String.valueOf(tipo.getId());
            String descripcion   = tipo.getDescripcion();
            Object[] elemento = {id, descripcion};
            modeloTabla.addRow(elemento);
        };
        tblTipos.setModel(modeloTabla);           
    }
    
    public void actualizarTablaFamilia(){
        listaFamilias = new Lista().listaFamiliasProducto();
        String[] columnas = {"ID","Descripcion"};
        DefaultTableModel modeloTabla = new DefaultTableModel(columnas, 0);
        
        for(FamiliaProductoDTO familia : listaFamilias){
            String id            = String.valueOf(familia.getId());
            String descripcion   = familia.getDescripcion();
            Object[] elemento = {id, descripcion};
            modeloTabla.addRow(elemento);
        };
        tblFamilias.setModel(modeloTabla);               
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        lblListaPersonas = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        btnCargarProducto = new javax.swing.JButton();
        btnRegistrarProducto = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        lblListaPersonas3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblIdProducto = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNombreProducto = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtPrecioCompra = new javax.swing.JTextField();
        txtPrecioVenta = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        cboTipoProducto = new javax.swing.JComboBox<>();
        btnEditarDatosProducto = new javax.swing.JButton();
        btnCancelarProducto = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        cboProveedores = new javax.swing.JComboBox<>();
        lblModoProducto = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cboFamiliaProducto = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnCargarFichaTipo = new javax.swing.JPanel();
        lblListaPersonas1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTipos = new javax.swing.JTable();
        btnCargarTipo = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        btnRegistrarTipo = new javax.swing.JButton();
        cboFamilia = new javax.swing.JPanel();
        lblListaPersonas4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblIdTipo = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtDescripcionTipo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cboFamiliaTipo = new javax.swing.JComboBox<>();
        btnEditarDatosTipo = new javax.swing.JButton();
        btnCancelarTipoProducto = new javax.swing.JButton();
        lblModoTipo = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        lblListaPersonas2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFamilias = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        btnCargarFamilia = new javax.swing.JButton();
        btnRegistrarFamilia = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        lblListaPersonas5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblIdFamilia = new javax.swing.JLabel();
        txtDescripcionFamilia = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnEditarDatosFamilia = new javax.swing.JButton();
        btnCancelarFamiliaProducto = new javax.swing.JButton();
        lblModoFamilia = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Manejo de productos");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_producto.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(139, 156, 168));

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane1.setOpaque(true);

        jPanel3.setBackground(new java.awt.Color(139, 156, 168));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel6.setBackground(new java.awt.Color(218, 210, 226));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblListaPersonas.setBackground(new java.awt.Color(146, 128, 183));
        lblListaPersonas.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblListaPersonas.setForeground(new java.awt.Color(255, 255, 255));
        lblListaPersonas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_producto.png"))); // NOI18N
        lblListaPersonas.setText("Lista de productos");
        lblListaPersonas.setOpaque(true);

        tblProductos.setBackground(new java.awt.Color(255, 255, 153));
        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblProductos);

        jLabel14.setBackground(new java.awt.Color(146, 128, 183));
        jLabel14.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Centro de acciones");
        jLabel14.setOpaque(true);

        btnCargarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_cargarficha.png"))); // NOI18N
        btnCargarProducto.setText("Cargar ficha de producto");
        btnCargarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarProductoActionPerformed(evt);
            }
        });

        btnRegistrarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_agregar.png"))); // NOI18N
        btnRegistrarProducto.setText("Registrar nuevo producto");
        btnRegistrarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblListaPersonas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCargarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegistrarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblListaPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCargarProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistrarProducto)
                .addGap(12, 12, 12))
        );

        jPanel10.setBackground(new java.awt.Color(218, 210, 226));
        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblListaPersonas3.setBackground(new java.awt.Color(146, 128, 183));
        lblListaPersonas3.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblListaPersonas3.setForeground(new java.awt.Color(255, 255, 255));
        lblListaPersonas3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_producto.png"))); // NOI18N
        lblListaPersonas3.setText("Datos del producto");
        lblListaPersonas3.setOpaque(true);

        jLabel1.setText("ID del producto (no editable):");

        lblIdProducto.setText("-");

        jLabel10.setText("Nombre del producto:");

        txtNombreProducto.setEditable(false);

        jLabel11.setText("Precio de compra:");

        jLabel12.setText("Precio de venta:");

        txtPrecioCompra.setEditable(false);

        txtPrecioVenta.setEditable(false);

        jLabel16.setText("Tipo de poducto:");

        cboTipoProducto.setEnabled(false);

        btnEditarDatosProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_editar.png"))); // NOI18N
        btnEditarDatosProducto.setText("Editar datos del producto");
        btnEditarDatosProducto.setEnabled(false);
        btnEditarDatosProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarDatosProductoActionPerformed(evt);
            }
        });

        btnCancelarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_cancelar.png"))); // NOI18N
        btnCancelarProducto.setText("Cancelar");
        btnCancelarProducto.setEnabled(false);
        btnCancelarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarProductoActionPerformed(evt);
            }
        });

        jLabel17.setText("Proveedor:");

        cboProveedores.setEnabled(false);

        lblModoProducto.setBackground(new java.awt.Color(204, 255, 204));
        lblModoProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_ver.png"))); // NOI18N
        lblModoProducto.setText("Usted está en modo vista.");
        lblModoProducto.setOpaque(true);

        jLabel18.setText("Familia de producto:");

        cboFamiliaProducto.setEnabled(false);
        cboFamiliaProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboFamiliaProductoActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_avanzar.png"))); // NOI18N
        jButton1.setText("Proveedores");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblModoProducto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblListaPersonas3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cboTipoProducto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel10Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblIdProducto))
                                .addComponent(jLabel10)
                                .addGroup(jPanel10Layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel10Layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel16)
                                .addComponent(btnCancelarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEditarDatosProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                                .addComponent(txtNombreProducto))
                            .addComponent(cboFamiliaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cboProveedores, 0, 255, Short.MAX_VALUE)
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblListaPersonas3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblIdProducto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboFamiliaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboTipoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditarDatosProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelarProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(lblModoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Productos", jPanel3);

        jPanel5.setBackground(new java.awt.Color(139, 156, 168));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnCargarFichaTipo.setBackground(new java.awt.Color(218, 210, 226));
        btnCargarFichaTipo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblListaPersonas1.setBackground(new java.awt.Color(146, 128, 183));
        lblListaPersonas1.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblListaPersonas1.setForeground(new java.awt.Color(255, 255, 255));
        lblListaPersonas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_tipo.png"))); // NOI18N
        lblListaPersonas1.setText("Lista de tipos de producto");
        lblListaPersonas1.setOpaque(true);

        tblTipos.setBackground(new java.awt.Color(255, 255, 153));
        tblTipos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblTipos);

        btnCargarTipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_cargarficha.png"))); // NOI18N
        btnCargarTipo.setText("Cargar ficha de tipo de producto");
        btnCargarTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarTipoActionPerformed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(146, 128, 183));
        jLabel13.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Centro de acciones");
        jLabel13.setOpaque(true);

        btnRegistrarTipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_agregar.png"))); // NOI18N
        btnRegistrarTipo.setText("Registrar nuevo tipo de producto");
        btnRegistrarTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarTipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnCargarFichaTipoLayout = new javax.swing.GroupLayout(btnCargarFichaTipo);
        btnCargarFichaTipo.setLayout(btnCargarFichaTipoLayout);
        btnCargarFichaTipoLayout.setHorizontalGroup(
            btnCargarFichaTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCargarFichaTipoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnCargarFichaTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(lblListaPersonas1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                    .addComponent(btnCargarTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegistrarTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        btnCargarFichaTipoLayout.setVerticalGroup(
            btnCargarFichaTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCargarFichaTipoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblListaPersonas1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCargarTipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistrarTipo)
                .addGap(12, 12, 12))
        );

        cboFamilia.setBackground(new java.awt.Color(218, 210, 226));
        cboFamilia.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblListaPersonas4.setBackground(new java.awt.Color(146, 128, 183));
        lblListaPersonas4.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblListaPersonas4.setForeground(new java.awt.Color(255, 255, 255));
        lblListaPersonas4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_producto.png"))); // NOI18N
        lblListaPersonas4.setText("Información de tipo");
        lblListaPersonas4.setOpaque(true);

        jLabel2.setText("ID de tipo (no editable):");

        lblIdTipo.setText("-");

        jLabel8.setText("Descripción:");

        txtDescripcionTipo.setEditable(false);

        jLabel9.setText("Familia de tipo:");

        cboFamiliaTipo.setEnabled(false);

        btnEditarDatosTipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_editar.png"))); // NOI18N
        btnEditarDatosTipo.setText("Editar datos de tipo");
        btnEditarDatosTipo.setEnabled(false);

        btnCancelarTipoProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_cancelar.png"))); // NOI18N
        btnCancelarTipoProducto.setText("Cancelar");
        btnCancelarTipoProducto.setEnabled(false);
        btnCancelarTipoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarTipoProductoActionPerformed(evt);
            }
        });

        lblModoTipo.setBackground(new java.awt.Color(204, 255, 204));
        lblModoTipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_ver.png"))); // NOI18N
        lblModoTipo.setText("Usted está en modo vista.");
        lblModoTipo.setOpaque(true);

        javax.swing.GroupLayout cboFamiliaLayout = new javax.swing.GroupLayout(cboFamilia);
        cboFamilia.setLayout(cboFamiliaLayout);
        cboFamiliaLayout.setHorizontalGroup(
            cboFamiliaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cboFamiliaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cboFamiliaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblModoTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblListaPersonas4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cboFamiliaLayout.createSequentialGroup()
                        .addGroup(cboFamiliaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(cboFamiliaLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblIdTipo))
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(txtDescripcionTipo)
                            .addComponent(cboFamiliaTipo, 0, 255, Short.MAX_VALUE)
                            .addComponent(btnEditarDatosTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCancelarTipoProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        cboFamiliaLayout.setVerticalGroup(
            cboFamiliaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cboFamiliaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblListaPersonas4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cboFamiliaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblIdTipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescripcionTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboFamiliaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditarDatosTipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelarTipoProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 281, Short.MAX_VALUE)
                .addComponent(lblModoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cboFamilia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCargarFichaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cboFamilia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCargarFichaTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Tipos de producto", jPanel5);

        jPanel4.setBackground(new java.awt.Color(139, 156, 168));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel8.setBackground(new java.awt.Color(218, 210, 226));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblListaPersonas2.setBackground(new java.awt.Color(146, 128, 183));
        lblListaPersonas2.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblListaPersonas2.setForeground(new java.awt.Color(255, 255, 255));
        lblListaPersonas2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_familia.png"))); // NOI18N
        lblListaPersonas2.setText("Lista de familias de producto");
        lblListaPersonas2.setOpaque(true);

        tblFamilias.setBackground(new java.awt.Color(255, 255, 153));
        tblFamilias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblFamilias);

        jLabel15.setBackground(new java.awt.Color(146, 128, 183));
        jLabel15.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Centro de acciones");
        jLabel15.setOpaque(true);

        btnCargarFamilia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_cargarficha.png"))); // NOI18N
        btnCargarFamilia.setText("Cargar ficha de familia de producto");
        btnCargarFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarFamiliaActionPerformed(evt);
            }
        });

        btnRegistrarFamilia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_agregar.png"))); // NOI18N
        btnRegistrarFamilia.setText("Registrar nueva familia de producto");
        btnRegistrarFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarFamiliaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(lblListaPersonas2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCargarFamilia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegistrarFamilia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblListaPersonas2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCargarFamilia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistrarFamilia)
                .addGap(12, 12, 12))
        );

        jPanel11.setBackground(new java.awt.Color(218, 210, 226));
        jPanel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblListaPersonas5.setBackground(new java.awt.Color(146, 128, 183));
        lblListaPersonas5.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblListaPersonas5.setForeground(new java.awt.Color(255, 255, 255));
        lblListaPersonas5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_producto.png"))); // NOI18N
        lblListaPersonas5.setText("Información de familia");
        lblListaPersonas5.setOpaque(true);

        jLabel3.setText("ID de familia (no editable):");

        lblIdFamilia.setText("-");

        txtDescripcionFamilia.setEditable(false);

        jLabel7.setText("Descripción:");

        btnEditarDatosFamilia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_editar.png"))); // NOI18N
        btnEditarDatosFamilia.setText("Editar datos de familia");
        btnEditarDatosFamilia.setEnabled(false);
        btnEditarDatosFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarDatosFamiliaActionPerformed(evt);
            }
        });

        btnCancelarFamiliaProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_cancelar.png"))); // NOI18N
        btnCancelarFamiliaProducto.setText("Cancelar");
        btnCancelarFamiliaProducto.setEnabled(false);
        btnCancelarFamiliaProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarFamiliaProductoActionPerformed(evt);
            }
        });

        lblModoFamilia.setBackground(new java.awt.Color(204, 255, 204));
        lblModoFamilia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_ver.png"))); // NOI18N
        lblModoFamilia.setText("Usted está en modo vista.");
        lblModoFamilia.setOpaque(true);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblModoFamilia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblListaPersonas5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblIdFamilia))
                            .addComponent(jLabel7)
                            .addComponent(txtDescripcionFamilia, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                            .addComponent(btnEditarDatosFamilia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCancelarFamiliaProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblListaPersonas5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblIdFamilia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescripcionFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditarDatosFamilia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelarFamiliaProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 327, Short.MAX_VALUE)
                .addComponent(lblModoFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Familias de producto", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    boolean estaEditando;
    private void btnCargarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarProductoActionPerformed
        if(!estaEditando){
        lblModoProducto.setText("Usted está en modo de edición.");
        lblModoProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_editar.png")));        
        btnEditarDatosProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_guardar.png")));    
        estaEditando = true;
        txtNombreProducto.setEditable(true);
        cboProveedores.setEnabled(true);
        cboTipoProducto.setEnabled(true);
        txtPrecioCompra.setEditable(true);
        txtPrecioVenta.setEditable(true);
        tblProductos.setEnabled(false);
        btnCargarProducto.setEnabled(false);
        btnRegistrarProducto.setEnabled(false);            
        btnCancelarProducto.setEnabled(true);
        btnEditarDatosProducto.setEnabled(true);
        }else{
        lblModoProducto.setText("Usted está en modo de vista.");
        lblModoProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_ver.png")));        
        btnEditarDatosProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_ver.png")));              
        estaEditando = false;
        txtNombreProducto.setEditable(false);
        cboProveedores.setEnabled(false);
        cboTipoProducto.setEnabled(false);
        txtPrecioCompra.setEditable(false);
        txtPrecioVenta.setEditable(false);
        tblProductos.setEnabled(true);
        btnCargarProducto.setEnabled(true);
        btnRegistrarProducto.setEnabled(true);      
        btnCancelarProducto.setEnabled(false);
        btnEditarDatosProducto.setEnabled(false);
        }

    }//GEN-LAST:event_btnCargarProductoActionPerformed

    private void btnEditarDatosProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarDatosProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarDatosProductoActionPerformed

    boolean estaRegistrando = false;
    private void btnRegistrarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarProductoActionPerformed
        if(!estaRegistrando){
            estaRegistrando = true;
            lblModoProducto.setText("Usted está en modo de registro.");
            lblModoProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_agregar.png")));
            btnEditarDatosProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_agregar.png")));
            btnEditarDatosProducto.setText("Confirmar registro");
            txtNombreProducto.setEditable(true);
            cboProveedores.setEnabled(true);
            cboFamiliaProducto.setEnabled(true);
            cboTipoProducto.setEnabled(true);
            txtPrecioCompra.setEditable(true);
            txtPrecioVenta.setEditable(true);
            tblProductos.setEnabled(false);
            btnCargarProducto.setEnabled(false);
            btnRegistrarProducto.setEnabled(false);         
            btnCancelarProducto.setEnabled(true);
            btnEditarDatosProducto.setEnabled(true);
        }else{
            estaRegistrando = false;
            lblModoProducto.setText("Usted está en modo vista.");
            lblModoProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn.ver.png")));
            btnEditarDatosProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_editar.png"))); 
            btnEditarDatosProducto.setText("Editar datos del producto");
            txtNombreProducto.setEditable(false);
            cboProveedores.setEnabled(false);
            cboFamiliaProducto.setEnabled(false);
            cboTipoProducto.setEnabled(false);
            txtPrecioCompra.setEditable(false);
            txtPrecioVenta.setEditable(false);
            tblProductos.setEnabled(true);
            btnCargarProducto.setEnabled(true);
            btnRegistrarProducto.setEnabled(true); 
            btnCancelarProducto.setEnabled(false);
            btnEditarDatosProducto.setEnabled(false);
        }
    }//GEN-LAST:event_btnRegistrarProductoActionPerformed

    private void btnCancelarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarProductoActionPerformed
        // TODO add your handling code here:
        estaRegistrando = false;
        estaEditando = false;
        lblModoProducto.setText("Usted está en modo de vista.");
        lblModoProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_ver.png")));
        btnEditarDatosProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_editar.png"))); 
        btnEditarDatosProducto.setText("Editar datos del producto");
        txtNombreProducto.setEditable(false);
        cboProveedores.setEnabled(false);
        cboTipoProducto.setEnabled(false);
        txtPrecioCompra.setEditable(false);
        txtPrecioVenta.setEditable(false);
        tblProductos.setEnabled(true);
        btnCargarProducto.setEnabled(true);
        btnRegistrarProducto.setEnabled(true); 
        btnCancelarProducto.setEnabled(false);
        btnEditarDatosProducto.setEnabled(false);
    }//GEN-LAST:event_btnCancelarProductoActionPerformed

    boolean estaRegistrandoTipo = false;
    private void btnRegistrarTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarTipoActionPerformed
        if(!estaRegistrandoTipo){
            estaRegistrando = true;
            lblModoTipo.setText("Usted está en modo de registro.");
            lblModoProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_agregar.png")));
            txtDescripcionTipo.setEditable(true);
            cboFamiliaTipo.setEnabled(true);
            btnEditarDatosTipo.setEnabled(true);
            btnCancelarTipoProducto.setEnabled(true);    
            btnEditarDatosTipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_agregar.png")));
            btnEditarDatosTipo.setText("Confirmar registro");
        }
    }//GEN-LAST:event_btnRegistrarTipoActionPerformed

    boolean estaEditandoTipo = false;
    private void btnCargarTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarTipoActionPerformed
        if(!estaEditandoTipo){
            estaRegistrando = true;
            lblModoTipo.setText("Usted está en modo de edición.");
            lblModoTipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_agregar.png")));
            txtDescripcionTipo.setEditable(true);
            cboFamiliaTipo.setEnabled(true);
            btnEditarDatosTipo.setEnabled(true);
            btnCancelarTipoProducto.setEnabled(true);    
            btnEditarDatosTipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_guardar.png")));
            btnEditarDatosTipo.setText("Confirmar edición");
        }else{
            estaEditandoTipo = false;
            lblModoTipo.setText("Usted está en modo de vista.");
            lblModoTipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_agregar.png")));            
            txtDescripcionTipo.setEditable(false);
            cboFamiliaTipo.setEnabled(false);
            btnEditarDatosTipo.setEnabled(false);
            btnCancelarTipoProducto.setEnabled(false);    
            btnEditarDatosTipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_editar.png")));
            btnEditarDatosTipo.setText("Editar datos de tipo");            
        }
    }//GEN-LAST:event_btnCargarTipoActionPerformed

    private void btnCancelarTipoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarTipoProductoActionPerformed
            estaEditandoTipo = false;
            lblModoTipo.setText("Usted está en modo de vista.");
            lblModoTipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_agregar.png")));            
            txtDescripcionTipo.setEditable(false);
            cboFamiliaTipo.setEnabled(false);
            btnEditarDatosTipo.setEnabled(false);
            btnCancelarTipoProducto.setEnabled(false);    
            btnEditarDatosTipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_editar.png")));
            btnEditarDatosTipo.setText("Confirmar edición");
    }//GEN-LAST:event_btnCancelarTipoProductoActionPerformed

    boolean estaRegistrandoFamilia = false;
    private void btnRegistrarFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarFamiliaActionPerformed
        // TODO add your handling code here:
        if(!estaRegistrandoFamilia){
            lblModoTipo.setText("Usted está en modo de registro.");
            lblModoTipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_agregar.png")));            
            estaRegistrandoFamilia = true;
            btnEditarDatosFamilia.setEnabled(true);
            txtDescripcionFamilia.setEditable(true);
            btnCancelarFamiliaProducto.setEnabled(true);
            btnEditarDatosFamilia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_agregar.png")));
            btnEditarDatosFamilia.setText("Confirmar registro");
        }
    }//GEN-LAST:event_btnRegistrarFamiliaActionPerformed

    private void btnCargarFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarFamiliaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCargarFamiliaActionPerformed

    private void btnCancelarFamiliaProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarFamiliaProductoActionPerformed
        estaRegistrandoFamilia = false;
        btnEditarDatosFamilia.setEnabled(false);
        txtDescripcionFamilia.setEditable(false);
        btnCancelarFamiliaProducto.setEnabled(false);
        btnEditarDatosFamilia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_editar.png")));
        btnEditarDatosFamilia.setText("Editar datos de familia");
        lblModoFamilia.setText("Usted está en modo de vista.");
        lblModoFamilia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_ver.png")));            
    }//GEN-LAST:event_btnCancelarFamiliaProductoActionPerformed

    boolean estaEditandoFamilia = false;
    private void btnEditarDatosFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarDatosFamiliaActionPerformed
        if(!estaEditandoFamilia){
            lblModoFamilia.setText("Usted está en modo de edición.");
            lblModoFamilia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_agregar.png")));                        
            estaEditandoFamilia = true;
            btnEditarDatosFamilia.setEnabled(true);
            txtDescripcionFamilia.setEditable(true);
            btnCancelarFamiliaProducto.setEnabled(true);
            btnEditarDatosFamilia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_guardar.png")));
            btnEditarDatosFamilia.setText("Confirmar edición");            
        }else{
            lblModoFamilia.setText("Usted está en modo de vista.");
            lblModoFamilia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_ver.png")));                                    
            estaEditandoFamilia = false;
            btnEditarDatosFamilia.setEnabled(false);
            txtDescripcionFamilia.setEditable(false);
            btnCancelarFamiliaProducto.setEnabled(false);
            btnEditarDatosFamilia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_editar.png")));
            btnEditarDatosFamilia.setText("Editar datos de familia");            
        }
    }//GEN-LAST:event_btnEditarDatosFamiliaActionPerformed

    private void cboFamiliaProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboFamiliaProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboFamiliaProductoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarFamiliaProducto;
    private javax.swing.JButton btnCancelarProducto;
    private javax.swing.JButton btnCancelarTipoProducto;
    private javax.swing.JButton btnCargarFamilia;
    private javax.swing.JPanel btnCargarFichaTipo;
    private javax.swing.JButton btnCargarProducto;
    private javax.swing.JButton btnCargarTipo;
    private javax.swing.JButton btnEditarDatosFamilia;
    private javax.swing.JButton btnEditarDatosProducto;
    private javax.swing.JButton btnEditarDatosTipo;
    private javax.swing.JButton btnRegistrarFamilia;
    private javax.swing.JButton btnRegistrarProducto;
    private javax.swing.JButton btnRegistrarTipo;
    private javax.swing.JPanel cboFamilia;
    private javax.swing.JComboBox<String> cboFamiliaProducto;
    private javax.swing.JComboBox<String> cboFamiliaTipo;
    private javax.swing.JComboBox<String> cboProveedores;
    private javax.swing.JComboBox<String> cboTipoProducto;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblIdFamilia;
    private javax.swing.JLabel lblIdProducto;
    private javax.swing.JLabel lblIdTipo;
    private javax.swing.JLabel lblListaPersonas;
    private javax.swing.JLabel lblListaPersonas1;
    private javax.swing.JLabel lblListaPersonas2;
    private javax.swing.JLabel lblListaPersonas3;
    private javax.swing.JLabel lblListaPersonas4;
    private javax.swing.JLabel lblListaPersonas5;
    private javax.swing.JLabel lblModoFamilia;
    private javax.swing.JLabel lblModoProducto;
    private javax.swing.JLabel lblModoTipo;
    private javax.swing.JTable tblFamilias;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTable tblTipos;
    private javax.swing.JTextField txtDescripcionFamilia;
    private javax.swing.JTextField txtDescripcionTipo;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtPrecioCompra;
    private javax.swing.JTextField txtPrecioVenta;
    // End of variables declaration//GEN-END:variables
}
