/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package odontologicaescritorio.vista;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import odontologicaescritorio.modelo.*;
import odontologicaescritorio.controlador.*;

/**
 *
 * @author Marco Antonio
 */
public class SeleccionarMesAgenda extends javax.swing.JInternalFrame {

    /**
     * Creates new form SeleccionarMesAgenda
     */
    private ArrayList<FuncionarioDTO> listaFuncionarios = new Lista().listarFuncionariosPorTipo(1);
    
    //Tipo acceso 0 - Recepcionista.
    //Tipo acceso 1 - Odontologo.
    private int tipoAcceso;
    public SeleccionarMesAgenda(int tipoAcceso, FuncionarioDTO funcionarioSesion) {
        initComponents();
        this.tipoAcceso = tipoAcceso;
        switch(this.tipoAcceso){
            case 0:
                actualizarCboFuncionarios();
                btnPlanificarMes.setVisible(false);
                break;
            case 1:
                cboFuncionario.addItem(funcionarioSesion.getRut() + " - " + funcionarioSesion.getP_nombre() + " " + funcionarioSesion.getP_apellido());
                break;
        }
    }
    
    public void actualizarCboFuncionarios(){
        for(FuncionarioDTO funcionario : listaFuncionarios){
            cboFuncionario.addItem(funcionario.getRut() + " - " + funcionario.getP_nombre() + " " + funcionario.getP_apellido());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cboFuncionario = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnPlanificarMes = new javax.swing.JButton();
        btnVerAgenda = new javax.swing.JButton();
        spnMes = new javax.swing.JSpinner();
        spnAno = new javax.swing.JSpinner();

        setBackground(new java.awt.Color(139, 156, 168));
        setClosable(true);
        setTitle("Consulta de agendas");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_reloj.png"))); // NOI18N
        setName(""); // NOI18N

        jPanel1.setBackground(new java.awt.Color(218, 210, 226));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setBackground(new java.awt.Color(146, 128, 183));
        jLabel8.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Centro de acciones");
        jLabel8.setIconTextGap(0);
        jLabel8.setOpaque(true);

        jLabel1.setText("Seleccione odontólogo:");

        jLabel2.setText("Seleccione mes:");

        jLabel3.setText("Seleccione año:");

        jLabel9.setBackground(new java.awt.Color(146, 128, 183));
        jLabel9.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_reloj.png"))); // NOI18N
        jLabel9.setText("Consultar/planificar agenda mensual");
        jLabel9.setIconTextGap(0);
        jLabel9.setOpaque(true);

        btnPlanificarMes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_editar.png"))); // NOI18N
        btnPlanificarMes.setText("Planificar mes");
        btnPlanificarMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlanificarMesActionPerformed(evt);
            }
        });

        btnVerAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_ver.png"))); // NOI18N
        btnVerAgenda.setText("Ver agenda");
        btnVerAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerAgendaActionPerformed(evt);
            }
        });

        spnMes.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));

        spnAno.setModel(new javax.swing.SpinnerNumberModel(2000, 2000, 2999, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboFuncionario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(spnMes))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(spnAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnPlanificarMes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnVerAgenda)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spnMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spnAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPlanificarMes)
                    .addComponent(btnVerAgenda))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlanificarMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlanificarMesActionPerformed
        // TODO add your handling code here:
        if(new Consulta().consultarMesAnoAgenda(Integer.parseInt(String.valueOf(spnMes.getValue())), Integer.parseInt(String.valueOf(spnAno.getValue())), Integer.parseInt(String.valueOf(cboFuncionario.getSelectedItem()).split(" ")[0])) == 0){
            javax.swing.JDesktopPane panelEscritorio = this.getDesktopPane();
            PlanificarMes planificarMes = new PlanificarMes(Integer.parseInt(String.valueOf(cboFuncionario.getSelectedItem()).split(" ")[0]), Integer.parseInt(String.valueOf(spnMes.getValue())), Integer.parseInt(String.valueOf(spnAno.getValue())));
            panelEscritorio.add(planificarMes);
            planificarMes.setVisible(true); 
        }else{
            JOptionPane.showMessageDialog(rootPane, "El mes seleccionado ya está planificado.", "Planificación de mes", HEIGHT);
        }
    
    }//GEN-LAST:event_btnPlanificarMesActionPerformed

    private void btnVerAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerAgendaActionPerformed
        if(!(new Consulta().consultarMesAnoAgenda(Integer.parseInt(String.valueOf(spnMes.getValue())), Integer.parseInt(String.valueOf(spnAno.getValue())), Integer.parseInt(String.valueOf(cboFuncionario.getSelectedItem()).split(" ")[0])) <= 0)){
            javax.swing.JDesktopPane panelEscritorio = this.getDesktopPane();
            ItinerarioHoras itinerarioHoras = new ItinerarioHoras(Integer.parseInt(String.valueOf(cboFuncionario.getSelectedItem()).split(" ")[0]), String.valueOf(cboFuncionario.getSelectedItem()).split(" ")[2], Integer.parseInt(String.valueOf(spnMes.getValue())), Integer.parseInt(String.valueOf(spnAno.getValue())), this.tipoAcceso);
            panelEscritorio.add(itinerarioHoras);
            itinerarioHoras.setVisible(true); 
        }else{
            JOptionPane.showMessageDialog(rootPane, "El mes seleccionado no está planificado.", "Planificación de mes", HEIGHT);
        }
    }//GEN-LAST:event_btnVerAgendaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPlanificarMes;
    private javax.swing.JButton btnVerAgenda;
    private javax.swing.JComboBox<String> cboFuncionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner spnAno;
    private javax.swing.JSpinner spnMes;
    // End of variables declaration//GEN-END:variables
}
