/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package odontologicaescritorio.vista;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import odontologicaescritorio.modelo.*;
import odontologicaescritorio.controlador.*;

/**
 *
 * @author Marco Antonio
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    private FuncionarioDTO funcionarioSesion;
    private UsuarioDTO usuarioSesion;
    private Login ventanaPadre;
    public VentanaPrincipal(FuncionarioDTO funcionarioSesion, UsuarioDTO usuarioSesion, Login ventanaPadre) {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.funcionarioSesion = funcionarioSesion;
        this.usuarioSesion = usuarioSesion;
        this.ventanaPadre = ventanaPadre;
        pnlSolicitudesBodega.setVisible(false);
        confirmarPermisos();
        lblFuncionarioConectado.setText(lblFuncionarioConectado.getText() + " " + funcionarioSesion.getRut() + " - " + funcionarioSesion.getDv() + " / " + funcionarioSesion.getP_nombre() + " " + funcionarioSesion.getP_apellido());
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/odontologicaescritorio/vista/img/icn_aplicacion.png")));
    }
    
    public void confirmarPermisos(){
        for(int permiso : usuarioSesion.getPermisos()){
            switch(permiso){
                case 0:
                    mnuAdministracion.setEnabled(true);
                    chkPermisoAdministrador.setSelected(true);
                    break;
                case 1:
                    mnuOdontologia.setEnabled(true);
                    chkPermisoOdontologo.setSelected(true);
                    break;
                case 2:
                    mnuRecepcion.setEnabled(true);
                    chkPermisoRecepcionista.setSelected(true);
                    break;
                case 3:
                    mnuLogistica.setEnabled(true);
                    chkPermisoLogistica.setSelected(true);
                    pnlSolicitudesBodega.setVisible(true);
                    lblSolicitudesBodega.setText("Hay " + new Consulta().solicitudesPendientesBodega() + " soliciutes pendientes en la bandeja de entrada.");
                    break;
                case 4:
                    chkPermisoCliente.setSelected(true);
                    break;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEscritorio = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        lblFuncionarioConectado = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnCambiarSesion = new javax.swing.JButton();
        chkPermisoAdministrador = new javax.swing.JCheckBox();
        chkPermisoOdontologo = new javax.swing.JCheckBox();
        chkPermisoRecepcionista = new javax.swing.JCheckBox();
        chkPermisoLogistica = new javax.swing.JCheckBox();
        chkPermisoCliente = new javax.swing.JCheckBox();
        btnCerrarSesion = new javax.swing.JButton();
        pnlSolicitudesBodega = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lblSolicitudesBodega = new javax.swing.JLabel();
        btnCerrarSesion2 = new javax.swing.JButton();
        barraMenu = new javax.swing.JMenuBar();
        mnuAdministracion = new javax.swing.JMenu();
        mnuManejoUsuarios = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        mnuOdontologia = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        mnuRecepcion = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        mnuLogistica = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Alice: para gestión de clínica odontológica");
        setIconImages(null);

        panelEscritorio.setBackground(new java.awt.Color(0, 102, 102));

        jPanel1.setBackground(new java.awt.Color(218, 210, 226));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 130));

        lblFuncionarioConectado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_persona.png"))); // NOI18N
        lblFuncionarioConectado.setText("Funcionario conectado:");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_lupa.png"))); // NOI18N
        jLabel2.setText("Niveles de acceso:");

        jLabel8.setBackground(new java.awt.Color(0, 0, 102));
        jLabel8.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_pc.png"))); // NOI18N
        jLabel8.setText("Sesión en curso");
        jLabel8.setIconTextGap(0);
        jLabel8.setOpaque(true);

        btnCambiarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_refrezcar.png"))); // NOI18N
        btnCambiarSesion.setText("Cambiar sesión");
        btnCambiarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarSesionActionPerformed(evt);
            }
        });

        chkPermisoAdministrador.setText("Administrador");
        chkPermisoAdministrador.setEnabled(false);

        chkPermisoOdontologo.setText("Odontólogo");
        chkPermisoOdontologo.setEnabled(false);

        chkPermisoRecepcionista.setText("Recepcionista");
        chkPermisoRecepcionista.setEnabled(false);

        chkPermisoLogistica.setText("Bodega");
        chkPermisoLogistica.setEnabled(false);

        chkPermisoCliente.setText("Cliente");
        chkPermisoCliente.setEnabled(false);

        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_cancelar.png"))); // NOI18N
        btnCerrarSesion.setText("Cerrar sesión");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFuncionarioConectado)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkPermisoAdministrador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkPermisoOdontologo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkPermisoRecepcionista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkPermisoLogistica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkPermisoCliente))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCambiarSesion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCerrarSesion)))
                .addGap(0, 200, Short.MAX_VALUE))
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(chkPermisoAdministrador)
                    .addComponent(chkPermisoOdontologo)
                    .addComponent(chkPermisoRecepcionista)
                    .addComponent(chkPermisoLogistica)
                    .addComponent(chkPermisoCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addComponent(lblFuncionarioConectado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCambiarSesion)
                    .addComponent(btnCerrarSesion))
                .addGap(13, 13, 13))
        );

        panelEscritorio.add(jPanel1);
        jPanel1.setBounds(10, 10, 720, 130);

        pnlSolicitudesBodega.setBackground(new java.awt.Color(218, 210, 226));
        pnlSolicitudesBodega.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setBackground(new java.awt.Color(0, 0, 102));
        jLabel9.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_carta.png"))); // NOI18N
        jLabel9.setText("Solicitudes a bodega");
        jLabel9.setIconTextGap(0);
        jLabel9.setOpaque(true);

        lblSolicitudesBodega.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_carta.png"))); // NOI18N
        lblSolicitudesBodega.setText("(Mensaje de número de solicitudes)");

        btnCerrarSesion2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_enviar.png"))); // NOI18N
        btnCerrarSesion2.setText("Abrir bandeja de solicitudes");
        btnCerrarSesion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesion2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSolicitudesBodegaLayout = new javax.swing.GroupLayout(pnlSolicitudesBodega);
        pnlSolicitudesBodega.setLayout(pnlSolicitudesBodegaLayout);
        pnlSolicitudesBodegaLayout.setHorizontalGroup(
            pnlSolicitudesBodegaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
            .addGroup(pnlSolicitudesBodegaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSolicitudesBodegaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSolicitudesBodega)
                    .addComponent(btnCerrarSesion2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSolicitudesBodegaLayout.setVerticalGroup(
            pnlSolicitudesBodegaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSolicitudesBodegaLayout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSolicitudesBodega)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCerrarSesion2)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        panelEscritorio.add(pnlSolicitudesBodega);
        pnlSolicitudesBodega.setBounds(10, 150, 720, 90);

        mnuAdministracion.setText("Módulo de administración");
        mnuAdministracion.setEnabled(false);

        mnuManejoUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_pc.png"))); // NOI18N
        mnuManejoUsuarios.setText("Manejo de usuarios");
        mnuManejoUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuManejoUsuariosActionPerformed(evt);
            }
        });
        mnuAdministracion.add(mnuManejoUsuarios);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_persona.png"))); // NOI18N
        jMenuItem3.setText("Manejo de funcionarios");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        mnuAdministracion.add(jMenuItem3);

        barraMenu.add(mnuAdministracion);

        mnuOdontologia.setText("Módulo de odontología");
        mnuOdontologia.setEnabled(false);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_persona.png"))); // NOI18N
        jMenuItem2.setText("Manejo de pacientes");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mnuOdontologia.add(jMenuItem2);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_reloj.png"))); // NOI18N
        jMenuItem6.setText("Mi agenda de horas");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        mnuOdontologia.add(jMenuItem6);

        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_carta.png"))); // NOI18N
        jMenuItem11.setText("Enviar solicitudes a bodega");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        mnuOdontologia.add(jMenuItem11);

        barraMenu.add(mnuOdontologia);

        mnuRecepcion.setText("Módulo de recepción");
        mnuRecepcion.setEnabled(false);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_persona.png"))); // NOI18N
        jMenuItem1.setText("Manejo de pacientes");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnuRecepcion.add(jMenuItem1);

        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_billete.png"))); // NOI18N
        jMenuItem12.setText("Emitir boleta de servicio");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        mnuRecepcion.add(jMenuItem12);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_servicio.png"))); // NOI18N
        jMenuItem4.setText("Manejo de servicios");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        mnuRecepcion.add(jMenuItem4);

        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_reloj.png"))); // NOI18N
        jMenuItem13.setText("Agenda de horas");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        mnuRecepcion.add(jMenuItem13);

        barraMenu.add(mnuRecepcion);

        mnuLogistica.setText("Módulo de bodegas");
        mnuLogistica.setEnabled(false);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_tipo.png"))); // NOI18N
        jMenuItem8.setText("Manejo de productos");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        mnuLogistica.add(jMenuItem8);

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_pedido.png"))); // NOI18N
        jMenuItem9.setText("Ordenes de pedido");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        mnuLogistica.add(jMenuItem9);

        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_carta.png"))); // NOI18N
        jMenuItem10.setText("Solicitudes a bodega");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        mnuLogistica.add(jMenuItem10);

        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/odontologicaescritorio/vista/img/icn_proveedor.png"))); // NOI18N
        jMenuItem14.setText("Manejo de proveedores");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        mnuLogistica.add(jMenuItem14);

        barraMenu.add(mnuLogistica);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEscritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEscritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        ManejadorPacienteFuncionario manejadorPacientes = new ManejadorPacienteFuncionario(1, 1, this.funcionarioSesion);
        panelEscritorio.add(manejadorPacientes);
        manejadorPacientes.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ManejadorPacienteFuncionario manejadorPacientes = new ManejadorPacienteFuncionario(2, 1, this.funcionarioSesion);
        panelEscritorio.add(manejadorPacientes);
        manejadorPacientes.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void mnuManejoUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuManejoUsuariosActionPerformed
        ManejadorUsuarios manejadorUsuarios = new ManejadorUsuarios();
        panelEscritorio.add(manejadorUsuarios);
        manejadorUsuarios.setVisible(true);
    }//GEN-LAST:event_mnuManejoUsuariosActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        ManejadorPacienteFuncionario manejadorPacientes = new ManejadorPacienteFuncionario(0, 0, this.funcionarioSesion);
        panelEscritorio.add(manejadorPacientes);
        manejadorPacientes.setVisible(true);        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void btnCambiarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarSesionActionPerformed
        // TODO add your handling code here:
        this.ventanaPadre.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCambiarSesionActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        ManejadorServicios manejadorServicios = new ManejadorServicios();
        panelEscritorio.add(manejadorServicios);
        manejadorServicios.setVisible(true);   
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        ManejadorProductos manejadorProductos = new ManejadorProductos();
        panelEscritorio.add(manejadorProductos);
        manejadorProductos.setVisible(true);           
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        EmisorBoletaServicio emisorBoletaServicio = new EmisorBoletaServicio();
        panelEscritorio.add(emisorBoletaServicio);
        emisorBoletaServicio.setVisible(true); 
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void btnCerrarSesion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesion2ActionPerformed
        SolicitudesBodega solicitudesBodega = new SolicitudesBodega();
        panelEscritorio.add(solicitudesBodega);
        solicitudesBodega.setVisible(true); 
    }//GEN-LAST:event_btnCerrarSesion2ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        ManejadorProveedores manejadorProveedores = new ManejadorProveedores();
        panelEscritorio.add(manejadorProveedores);
        manejadorProveedores.setVisible(true); 
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        SolicitudesBodega solicitudesBodega = new SolicitudesBodega();
        panelEscritorio.add(solicitudesBodega);
        solicitudesBodega.setVisible(true); 
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        EnviarSolicitudBodega enviarSolicitud = new EnviarSolicitudBodega(funcionarioSesion.getRut(), funcionarioSesion.getP_nombre(), funcionarioSesion.getP_apellido());
        panelEscritorio.add(enviarSolicitud);
        enviarSolicitud.setVisible(true); 
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        ManejadorOrdenesPedido manejadorOrdenesPedido = new ManejadorOrdenesPedido();
        panelEscritorio.add(manejadorOrdenesPedido);
        manejadorOrdenesPedido.setVisible(true); 
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        SeleccionarMesAgenda seleccionarMesAgenda = new SeleccionarMesAgenda(1, funcionarioSesion);
        panelEscritorio.add(seleccionarMesAgenda);
        seleccionarMesAgenda.setVisible(true); 
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        SeleccionarMesAgenda seleccionarMesAgenda = new SeleccionarMesAgenda(0, funcionarioSesion);
        panelEscritorio.add(seleccionarMesAgenda);
        seleccionarMesAgenda.setVisible(true); 
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
        this.ventanaPadre.dispose();
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton btnCambiarSesion;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnCerrarSesion2;
    private javax.swing.JCheckBox chkPermisoAdministrador;
    private javax.swing.JCheckBox chkPermisoCliente;
    private javax.swing.JCheckBox chkPermisoLogistica;
    private javax.swing.JCheckBox chkPermisoOdontologo;
    private javax.swing.JCheckBox chkPermisoRecepcionista;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFuncionarioConectado;
    private javax.swing.JLabel lblSolicitudesBodega;
    private javax.swing.JMenu mnuAdministracion;
    private javax.swing.JMenu mnuLogistica;
    private javax.swing.JMenuItem mnuManejoUsuarios;
    private javax.swing.JMenu mnuOdontologia;
    private javax.swing.JMenu mnuRecepcion;
    private javax.swing.JDesktopPane panelEscritorio;
    private javax.swing.JPanel pnlSolicitudesBodega;
    // End of variables declaration//GEN-END:variables

}
